
export const links = [
  { icon: "/images/linux1.png", label: "Linux", details: "Linux details" },
  { icon: "/images/docker.webp", label: "Docker", details: "Docker details" },
  { icon: "/images/Python.webp", label: "Python", details: "Python details" },
  { icon: "/images/Github.png", label: "GitHub", details: "GitHub details" },
  { icon: "/images/Terraform.png", label: "Terraform", details: "Terraform details" },
  { icon: "/images/Kubernetes.webp", label: "Kubernetes", details: "Kubernetes details" },
  { icon: "/images/Java.png", label: "Java", details: "Java details" },
  { icon: "/images/ChatGPT.webp", label: "ChatGPT", details: "ChatGPT details" },
  { icon: "/images/Ansible.png", label: "Ansible", details: "Ansible details" },
  { icon: "/images/AWS.webp", label: "AWS", details: "AWS details" },
  { icon: "/images/AWS.webp", label: "AWSCloud", details: "AWS details" },
  { icon: "/images/Jenkins.png", label: "Jenkins", details: "Jenkins details" },
  { icon: "/images/MySQL.png", label: "MySQL", details: "MySQL details" },
  { icon: "/images/MEAN & MERN.png", label: "MEAN & MERN", details: "MEAN & MERN details" },
  { icon: "/images/Azure.png", label: "AzureCloud", details: "Azure details" },
  { icon: "/images/Cloud%20Computing.png", label: "Cloud Computing", details: "Cloud Computing details" },
  { icon: "/images/Devops.png", label: "Devops", details: "DevOps details" },
  { icon: "/images/GCP.png", label: "GCP", details: "GCP details" },
  { icon: "/images/CI/CD.png", label: "CI/CD", details: "CI/CD details" },
  { icon: "/images/Backstage.png", label: "Backstage", details: "Backstage details" },
  { icon: "/images/AI/ML.png", label: "AI/ML", details: "AI/ML details" },
  { icon: "/images/AppSecurity.png", label: "AppSecurity", details: "AppSecurity details" },
  { icon: "/images/DS%2FALGO.png", label: "DS/ALGO", details: "DS/ALGO details" },
];

export const RoleBased = [
  { icon: "/images/image.png", label: "System_Administrator", details: "Linux details" },
  { icon: "/images/image.png", label: "Kubernetes_Administrator", details: "Linux details" },
  { icon: "/images/image.png", label: "Site Reliability_Engineer", details: "Linux details" },
  { icon: "/images/image.png", label: "Kubernetes_Developer", details: "Linux details" },
  { icon: "/images/image.png", label: "Platform_Engineer", details: "Linux details" },
  { icon: "/images/image.png", label: "DevOps_Engineer", details: "Linux details" },
  { icon: "/images/image.png", label: "Cloud_Engineer", details: "Linux details" },
];
